### ISSUE TITLE
Error when build (`gulp build`)

### ISSUE THREAD

**Issue by k33g** [streamdataio/streamdataio-js-sdk#4]
Hello
I'm trying to build the sdk and I get an error when I use the `gulp build` command.

    [18:22:42] Using gulpfile ~/Dropbox/Public/TYPEUNSAFE-SITE/streamdataio-js-sdk/gulpfile.js
    [18:22:42] Starting 'build'...
    [18:22:42] Starting 'clean'...
    [18:22:42] Starting 'clean:dist'...
    [18:22:42] Finished 'clean:dist' after 11 ms
    [18:22:42] Starting 'clean:tmp'...
    [18:22:42] Finished 'clean:tmp' after 1.25 ms
    [18:22:42] Starting 'clean:doc'...
    [18:22:42] Finished 'clean:doc' after 272 μs
    [18:22:42] Finished 'clean' after 15 ms
    [18:22:42] Starting 'buildScript'...
    [18:22:42] gulp-debug: src/Exporter.js
    [18:22:42] gulp-debug: src/Logger.js
    [18:22:42] gulp-debug: src/Preconditions.js
    [18:22:42] gulp-debug: src/Listeners.js
    [18:22:42] gulp-debug: src/StreamdataEventSource.js
    [18:22:42] gulp-debug: src/StreamdataError.js
    [18:22:42] gulp-debug: src/Streamdata.js
    [18:22:42] gulp-debug: 7 items
    [18:22:42] Finished 'buildScript' after 86 ms
    [18:22:42] Starting 'minify'...
    [18:22:42] gulp-debug: 0 items

    /Users/k33g_org/Dropbox/Public/TYPEUNSAFE-SITE/streamdataio-js-sdk/node_modules/gulp-closurecompiler/gulp-closurecompiler.js:48
                  base: firstFile.base,
                                 ^
    TypeError: Cannot read property 'base' of undefined
        at Stream.<anonymous> (/Users/k33g_org/Dropbox/Public/TYPEUNSAFE-SITE/streamdataio-js-sdk/node_modules/gulp-closurecompiler/gulp-closurecompiler.js:48:23)
        at /Users/k33g_org/Dropbox/Public/TYPEUNSAFE-SITE/streamdataio-js-sdk/node_modules/gulp-closurecompiler/node_modules/closurecompiler/ClosureCompiler.js:281:21
        at ChildProcess.<anonymous> (/Users/k33g_org/Dropbox/Public/TYPEUNSAFE-SITE/streamdataio-js-sdk/node_modules/gulp-closurecompiler/node_modules/closurecompiler/ClosureCompiler.js:273:15)
        at ChildProcess.EventEmitter.emit (events.js:98:17)
        at Process.ChildProcess._handle.onexit (child_process.js:789:12)

I've tried with node v0.10.9, v0.10.13, v0.11.16, v4.0.0 and v4.1.1

**Comment by dominiquemongelli** [comment]
Hello,

Unfortunately, we cannot manage to reproduce the issue with the node versions provided.
The issue seems to be linked to the node module gulp-closurecompiler.
Can you provide the version number fetched by npm in your project for the following modules in package.json :
- gulp-closurecompiler
- gulp-closure-compiler

Thank you.

**Comment by k33g** [comment]
Hi,

    "gulp-closure-compiler": "^0.2.16",
    "gulp-closurecompiler": "^0.1.0",

**Comment by dominiquemongelli** [comment]
Hello,

Actually, I'm talking about the modules fetched by npm, in the folder node_modules :-).
These versions are available at the following path : 
- node_modules/gulp-closure-compiler/package.json
- node_modules/gulp-closurecompiler/package.json

Thank you.

**Comment by k33g** [comment]
"name": "gulp-closure-compiler",
  "version": "0.2.20",

and 

  "name": "gulp-closurecompiler",
  "version": "0.1.0",

**Comment by dominiquemongelli** [comment]
Hello,

Thanks for the informations.
You have the same modules version than the one we have on our desktop.
We spotted that you might be on Mac system.
As we did tests on linux OS, let us try on Mac.

We keep you informed.

**Comment by dominiquemongelli** [comment]
Hello,

The issue you are facing is actually not linked to operating system.
We have managed to reproduce the issue by removing the folder bower_components before doing the command "gulp build".
Can you please double check that the command "bower update" is working fine ?
You must have the following files in the project : 
ls -l bower_components/eventsource-polyfill/
total 16
-rw-rw-r-- 1 dominique dominique  647 nov.  17 09:37 bower.json
drwxrwxr-x 2 dominique dominique 4096 nov.  17 09:37 dist
-rw-rw-r-- 1 dominique dominique 1072 nov.  17 09:37 LICENSE
-rw-rw-r-- 1 dominique dominique 1973 nov.  17 09:37 README.md

In folder dist, there are 3 javascript files : browserify-eventsource.js, eventsource.js, eventsource.min.js.

Keep us informed.

**Comment by k33g** [comment]
Hi @dominiquemongelli 
`bower update works fine`
I've got the 3 files in the `dist` folder
but I've got the same error
as soon as possible, I'll try with an other Mac laptop

Regards

**Comment by dominiquemongelli** [comment]
Hello,

Just for information here is the trace when gulp build command is OK :
[11:51:10] Using gulpfile ~/streamdataio-js-sdk/gulpfile.js
[11:51:10] Starting 'build'...
[11:51:10] Starting 'clean'...
[11:51:10] Starting 'clean:dist'...
[11:51:10] Finished 'clean:dist' after 63 ms
[11:51:10] Starting 'clean:tmp'...
[11:51:10] Finished 'clean:tmp' after 1.77 ms
[11:51:10] Starting 'clean:doc'...
[11:51:10] Finished 'clean:doc' after 28 ms
[11:51:10] Finished 'clean' after 99 ms
[11:51:10] Starting 'buildScript'...
[11:51:10] gulp-debug: bower_components/eventsource-polyfill/dist/eventsource.js
[11:51:10] gulp-debug: src/Exporter.js
[11:51:10] gulp-debug: src/Logger.js
[11:51:10] gulp-debug: src/Preconditions.js
[11:51:10] gulp-debug: src/Listeners.js
[11:51:10] gulp-debug: src/StreamdataEventSource.js
[11:51:10] gulp-debug: src/StreamdataError.js
[11:51:10] gulp-debug: src/Streamdata.js
[11:51:10] gulp-debug: 8 items
[11:51:10] Finished 'buildScript' after 160 ms
[11:51:10] Starting 'minify'...
[11:51:10] gulp-debug: bower_components/eventsource-polyfill/dist/eventsource.js
[11:51:10] gulp-debug: 1 items
[11:51:12] Finished 'minify' after 2.01 s
[11:51:12] Starting 'obfuscate'...
[11:51:12] gulp-debug: dist/libs.js
[11:51:12] gulp-debug: src/Exporter.js
[11:51:12] gulp-debug: src/Logger.js
[11:51:12] gulp-debug: src/Preconditions.js
[11:51:12] gulp-debug: src/Listeners.js
[11:51:12] gulp-debug: src/StreamdataEventSource.js
[11:51:13] gulp-debug: src/StreamdataError.js
[11:51:13] gulp-debug: src/Streamdata.js
[11:51:13] gulp-debug: 8 items
[11:51:18] Finished 'obfuscate' after 5.73 s
[11:51:18] Starting 'doc'...
[11:51:19] gulp-debug: src/api.js
[11:51:19] gulp-debug: README.md
[11:51:19] gulp-debug: 2 items
[11:51:19] Finished 'doc' after 855 ms
[11:51:19] Finished 'build' after 8.87 s

See that eventsource.js is used within the compilation process.
Keep us informed once you'll try with another laptop.

Regards

**Comment by k33g** [comment]
build successful with node v0.11.16 and v4.0.0 :+1:  :clap:

**Comment by dominiquemongelli** [comment]
A last update :  the root cause of the issue is due to the configuration of bower.
Indeed, the target directory for bower update must put dependencies in PROJECT_FOLDER/bower_components.
If it's not the case, you can update the bower configuration in your .bowerrc file in the root folder of the project via the following conf : 
{
    "directory": "bower_components"
}
